name: calbot
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  syncfusion_flutter_calendar: ^31.2.12
  flutter_riverpod: ^3.0.3
  intl: ^0.20.2
  flutter_colorpicker: ^1.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/halulu.png