name: halulu
description: "Smart cross-platform scheduling bot with Discord integration."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  syncfusion_flutter_calendar: ^31.2.12
  flutter_riverpod: ^3.0.3
  intl: ^0.20.2
  get: ^4.7.3
  get_storage: ^2.0.3
  http: ^1.2.2
  uuid: ^4.5.2

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/halulu.png
    - assets/images/halulu_128x128.png
